---
- name: change BIOS setting
  hosts: localhost
  tasks:
    - name: boot from BIOS
      vmware_guest_boot_manager:
        hostname: 192.168.100.202
        username: root
        password: T!g3r@Ind!A
        validate_certs: no
        name: sql1
        boot_delay: 2000
        enter_bios_setup: True
        boot_retry_enabled: True
        boot_retry_delay: 22300
        boot_firmware: bios
        boot_order:
          - disk
          - floppy
          - ethernet
          - cdrom

    - name: Power on / Power off / Restart a virtual machine
      vmware_guest_powerstate:
        hostname: 192.168.100.202
        username: root
        password: T!g3r@Ind!A
        folder: Ansible
        name: sql1
        state: powered-off

    - name: Power on / Power off / Restart a virtual machine
      vmware_guest_powerstate:
        hostname: 192.168.100.202
        username: root
        password: T!g3r@Ind!A
        folder: Ansible
        name: sql1
        state: powered-on

    - name: Power on / Power off / Restart a virtual machine
      vmware_guest_powerstate:
        hostname: 192.168.100.202
        username: root
        password: T!g3r@Ind!A
        folder: Ansible
        name: sql1
        state: powered-off

    - name: Power on / Power off / Restart a virtual machine
      vmware_guest_powerstate:
        hostname: 192.168.100.202
        username: root
        password: T!g3r@Ind!A
        folder: Ansible
        name: sql1
        state: powered-on

